"""merchantfee

Revision ID: 0236576b4973
Revises: 28d90092508b
Create Date: 2024-06-08 14:48:57.830907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0236576b4973'
down_revision: Union[str, None] = '28d90092508b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchantprofile', sa.Column('fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchantprofile', 'fee')
    # ### end Alembic commands ###
