"""fullnametest

Revision ID: 179b2f566302
Revises: 03f509e820d0
Create Date: 2024-06-04 12:56:25.956625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '179b2f566302'
down_revision: Union[str, None] = '03f509e820d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testmodel', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('testmodel', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('testmodel', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testmodel', 'full_name')
    op.drop_column('testmodel', 'last_name')
    op.drop_column('testmodel', 'first_name')
    # ### end Alembic commands ###
