"""merchant_transaction

Revision ID: 31c0c2172f02
Revises: d9f2f24a2ce3
Create Date: 2024-06-13 16:59:59.948349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31c0c2172f02'
down_revision: Union[str, None] = 'd9f2f24a2ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchanttransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.Integer(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('credit_amt', sa.Integer(), nullable=False),
    sa.Column('pay_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['merchant'], ['merchantprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchanttransactions')
    # ### end Alembic commands ###
