"""banda

Revision ID: 386b3d8ed5cc
Revises: aabe575ffd26
Create Date: 2024-06-01 10:50:01.546739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '386b3d8ed5cc'
down_revision: Union[str, None] = 'aabe575ffd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transection', sa.Column('credited_amount', sa.Integer(), nullable=True))
    op.add_column('transection', sa.Column('credited_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transection', 'credited_currency')
    op.drop_column('transection', 'credited_amount')
    # ### end Alembic commands ###
