"""lastlogin

Revision ID: 3a7fe7198d28
Revises: 9aafb762fa7d
Create Date: 2024-05-15 17:25:18.869170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7fe7198d28'
down_revision: Union[str, None] = '9aafb762fa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastlogin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastlogin')
    # ### end Alembic commands ###
