"""empty message

Revision ID: 6e3231a73ef3
Revises: b27b0a69fd3f
Create Date: 2024-04-08 17:36:18.943236

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3231a73ef3'
down_revision: Union[str, None] = 'b27b0a69fd3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
  pass
    # ### end Alembic commands ###
