"""merchantstatus

Revision ID: 7f829045c339
Revises: 0236576b4973
Create Date: 2024-06-08 14:56:57.946091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f829045c339'
down_revision: Union[str, None] = '0236576b4973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchantprofile', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchantprofile', 'status')
    # ### end Alembic commands ###
