"""currency receiver

Revision ID: 83defe93fe09
Revises: a02eedef07d7
Create Date: 2024-05-24 10:35:20.671547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83defe93fe09'
down_revision: Union[str, None] = 'a02eedef07d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transection', sa.Column('rec_pay_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transection', 'rec_pay_mode')
    # ### end Alembic commands ###
