"""Tmtime

Revision ID: 8de30b5ff705
Revises: 2242bced1e1d
Create Date: 2024-05-08 14:02:38.695449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de30b5ff705'
down_revision: Union[str, None] = '2242bced1e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transection', sa.Column('txdtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transection', 'txdtime')
    # ### end Alembic commands ###
