"""empty message

Revision ID: 96d11b1e5d03
Revises: 66154fbdbe3a
Create Date: 2024-04-08 17:58:52.939077

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d11b1e5d03'
down_revision: Union[str, None] = '66154fbdbe3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                                     server_default='John'))
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='Cena')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
