"""currency receiver

Revision ID: a02eedef07d7
Revises: 2ed91ac8cc40
Create Date: 2024-05-24 10:16:00.752817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02eedef07d7'
down_revision: Union[str, None] = '2ed91ac8cc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiverdetails', sa.Column('currency', sa.Integer(), nullable=True))
    op.add_column('receiverdetails', sa.Column('amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'receiverdetails', 'currency', ['currency'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receiverdetails', type_='foreignkey')
    op.drop_column('receiverdetails', 'amount')
    op.drop_column('receiverdetails', 'currency')
    # ### end Alembic commands ###
