"""currencyinWallet

Revision ID: a4be2f0fbcb1
Revises: c517b00fbaba
Create Date: 2024-05-11 09:48:20.625860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4be2f0fbcb1'
down_revision: Union[str, None] = 'c517b00fbaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'currency')
    # ### end Alembic commands ###
