"""statuskyc

Revision ID: a9af152cd5d4
Revises: b7d525b0810c
Create Date: 2024-05-09 12:37:34.313535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9af152cd5d4'
down_revision: Union[str, None] = 'b7d525b0810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kycdetails', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kycdetails', 'status')
    # ### end Alembic commands ###
