"""walletcreateddate

Revision ID: ae6346544c42
Revises: cc619ce97f83
Create Date: 2024-05-20 18:11:54.149058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6346544c42'
down_revision: Union[str, None] = 'cc619ce97f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('created_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'created_data')
    # ### end Alembic commands ###
