"""Transactionstatusdatatype

Revision ID: c517b00fbaba
Revises: a9af152cd5d4
Create Date: 2024-05-10 15:27:17.954441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c517b00fbaba'
down_revision: Union[str, None] = 'a9af152cd5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transection', 'txdstatus',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transection', 'txdstatus',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
