"""merchantisactive

Revision ID: cf3527eeb9e1
Revises: 7f829045c339
Create Date: 2024-06-08 15:33:06.260840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3527eeb9e1'
down_revision: Union[str, None] = '7f829045c339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchantprofile', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchantprofile', 'is_active')
    # ### end Alembic commands ###
